project:
  type: website
  output-dir: render

website:
  title: "Les Mouettes Savantes"

        
  navbar:
    background:  "#1B5E20"
    left:
      - href: index.qmd
        text: Présentation
      - href: descriptionProjet.qmd
        text: Démarche
      - href: orga.qmd
        text: Détails pratiques
      - href: sponsors.qmd
        text: Les sponsors
      - href: mathC2plus.qmd
        text: Label MathC2+
  page-footer:
      center: 
        - text: "Contact"
          href: mailto:lesmouettessavantes@gmail.com



format:
  html:
    theme: sandstone
    fontcolor: "#2D4200"
    linkcolor: "#A3BD00"
    css: styles.css
    toc: true



